In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
a.shape
b.shape

(3,)

In [4]:
#두 개를 좌우로 합치는 concatenate
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [5]:
#상하로 합치는 
np.concatenate([a.reshape(1,3),b.reshape(1,3)],1).shape

(1, 6)

In [6]:
#상하로 합치는 
np.concatenate([a.reshape(1,3),b.reshape(1,3)],0).shape

(2, 3)

In [8]:
#좌우로 쌓는 stack
np.stack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#stack
np.stack([a,b],axis=0).shape

(2, 3)

In [10]:
#stack
np.stack([a,b],1).shape

(3, 2)

In [11]:
#
np.stack([a.reshape(1,3),b.reshape(1,3)]).shape

(2, 1, 3)

In [12]:
# 세로 쌓는 V stack
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# H stack
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [16]:
#
np.hstack([a.reshape(1,3),b.reshape(1,3)])

array([[1, 2, 3, 4, 5, 6]])

In [18]:
#
np.hstack([a.reshape(3,1),b.reshape(3,1)])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
#
np.r_[a.reshape(1,3),b.reshape(1,3)]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#
np.hstack([a.reshape(3,1),b.reshape(3,1)])
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
arr1=np.zeros((3,2))

In [24]:
arr2=np.ones(3)

In [25]:
arr2

array([1., 1., 1.])

In [29]:
arr3 = np.ones((3,2))

In [30]:
np.stack([arr1,arr3],1).shape

(3, 2, 2)

In [32]:
np.concatenate([arr1,arr2.reshape(3,1)],1)
np.hstack([arr1,arr2.reshape(3,1)])
np.c_[arr1,arr2]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [33]:
arr1_1=np.zeros(3)
arr1_2=np.zeros(3)
arr2_1=np.ones(3)
np.stack([arr1_1,arr1_2,arr2_1],axis=1)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [34]:
arr2=np.ones(2)

In [35]:
# 방법 1 - vstack 사용
np.vstack([arr1,arr2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.]])

In [37]:
# 방법 2 - concatenate 사용
np.concatenate([arr1,arr2.reshape(1,2)])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.]])

In [39]:
# 방법 3 - r_ 사용
np.r_[arr1,arr2.reshape(1,2)]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.]])

In [40]:
##
x=np.arange(6).reshape(3,2)

In [41]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
x.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
# .T
x.T

array([[0, 2, 4],
       [1, 3, 5]])

In [44]:
# 위의 .T와 reshape의 차이
x.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
# transpose
x.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [48]:
#
x=np.random.randn(4,3,2)

In [57]:
x.T.shape

(2, 3, 4)

In [58]:
## 
x.T

array([[[-0.09103055, -1.45527236,  1.78964992, -0.45971731],
        [ 0.33952222,  0.00557905, -0.45974987,  0.41059234],
        [ 1.51473818,  0.05396886,  0.76691019,  1.40790227]],

       [[ 0.85468209, -1.83964274,  1.44744425, -1.38262787],
        [-1.59217801,  0.01960341,  0.43152986, -1.36881215],
        [ 0.08097495, -0.19778105,  0.08866925, -0.30790093]]])

In [59]:
np.dot(x,x.T)

ValueError: shapes (4,3,2) and (2,3,4) not aligned: 2 (dim 2) != 3 (dim 1)

In [60]:
x.dot(x.T)

ValueError: shapes (4,3,2) and (2,3,4) not aligned: 2 (dim 2) != 3 (dim 1)

In [61]:
x@x.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [62]:
##
x=10
y=11

In [63]:
x>y

False

In [64]:
if x>y:
    print("OK")

In [65]:
if [1,2,3] == [3]:
    print("OK")

In [70]:
x = [1,2,3]
for i in x:
    if i <= 2:
        print(i)

1
2


In [71]:
np.array(x) <= 2

array([ True,  True, False])

In [72]:
# All
np.all(np.array(x) <= 2)

np.False_

In [73]:
# Any
np.any(np.array(x) <= 2)

np.True_

In [77]:
n=3
np.arange(2,n+1)

array([2, 3])

In [88]:
# 연습 #
# : 어떤 수를 넣을 경우 소수인지 아닌지 판단하는 법

cnt=0

n=13

for i in range(2,n+1):
    if n % i == 0:
        cnt += 1
if cnt == 1:
    print("소수입니다.")
else:
    print("소수가 아닙니다.")

소수입니다.


In [92]:
# 변형

x=7

x = len([ i for i in range(2, n+1) if n % i == 0])

if x ==1:
    print("소수")
else:
    print("소수 아님")

소수


In [93]:
(n % np.arange(2, n+1)) == 0

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [94]:
a=np.array([1,2,3])

In [95]:
a[(a>1)&(a<3)]

array([2])

In [96]:
#logical_and
a[np.logical_and(a>1,a<3)]

array([2])

In [97]:
#logical_or
np.logical_or(a>1,a<3)

array([ True,  True,  True])

In [98]:
a[a != 2]

array([1, 3])

In [99]:
#logical_not
np.logical_not(a==2)

array([ True, False,  True])

In [101]:
a = np.arange(1,11)

In [102]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
#where
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10])

In [104]:
np.where(a>5,True,False)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [105]:
a[np.where(a>5,True,False)]

array([ 6,  7,  8,  9, 10])

In [133]:
# 연습 #
#: 배열 만들기 
# - 60부터 100점 사이에서 
# 100명의 학생 시험 점수(4과목) 평균에 따라 성적 배정
# 70점 이하면 fail

np.random.seed(100) #100명의 성적을 난수생성
score = np.random.randint(60,101,size=(100,4)) #점수 난수생성

In [108]:
score

array([[ 68,  84,  63,  99],
       [ 83,  75,  70,  90],
       [ 94,  62,  94,  74],
       [ 94,  84,  75,  96],
       [ 76,  69,  89,  82],
       [ 62,  87,  64,  91],
       [ 61,  73,  79,  96],
       [ 64,  87,  63,  67],
       [ 61,  74,  67,  76],
       [ 62,  90,  79,  94],
       [ 87,  90,  99,  98],
       [ 78,  60,  94,  70],
       [ 77,  68,  73,  90],
       [ 77,  64, 100,  87],
       [ 87,  79,  74,  60],
       [ 73,  72,  63,  66],
       [ 63,  80,  75,  70],
       [ 83,  63,  96,  65],
       [ 67,  98,  82,  90],
       [ 94,  80,  91,  72],
       [ 93,  98,  82,  60],
       [ 94,  79,  64,  64],
       [ 95,  83,  69,  81],
       [ 85,  66,  97,  98],
       [ 99,  90,  90,  62],
       [ 84,  77,  97,  85],
       [ 95,  76,  72,  82],
       [ 78,  63,  88,  91],
       [ 80,  70,  68,  85],
       [ 68,  90,  72,  78],
       [ 89,  88,  60,  69],
       [100,  88,  62,  76],
       [ 65,  86,  94,  63],
       [ 90,  74,  73,  80],
       [ 61,  

In [118]:
mean_score = np.mean(score,axis=1)

In [119]:
grade = np.where(mean_score <= 70, "fail", "success")

In [120]:
print(grade)

['success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'fail' 'success' 'success' 'success' 'success' 'success'
 'success' 'fail' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'fail' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'fail'
 'success' 'success' 'success' 'success' 'fail' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success' 'success' 'success' 'success' 'success' 'success'
 'success' 'success']

In [123]:
# 다른 풀이

np.where((np.mean(score,1) > 70), 'success','fail')

array(['success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'fail', 'success', 'success', 'success',
       'success', 'success', 'success', 'fail', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'fail', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'success', 'success',
       'success', 'success', 'success', 'success', 'fail', 'success',
       'success', 'success', 'success', 'fail', 'success', 'suc

In [125]:
np.sum(np.where((np.mean(score,1) > 70), 'success','fail') == 'fail')

np.int64(5)

In [142]:
# 4과목 점수 평균에 따른 성적 구하기
# 90이상 a, 80이상 b, 나머지 c
np.random.seed(100)
score = np.random.randint(60,101,size=(100,4)) #점수 난수생성
mean_score = np.mean(score,axis=1)

In [143]:
grade = np.where(mean_score >= 90, 'A',
        np.where(mean_score >= 80, 'B', 'C'))

In [147]:
unique, count = np.unique(grade,return_counts=True)
result = {str(grade): int(count) for grade, count in zip(unique,count)}

In [151]:
print("성적:", grade)
print("결과", result)

성적: ['C' 'C' 'B' 'B' 'C' 'C' 'C' 'C' 'C' 'B' 'A' 'C' 'C' 'B' 'C' 'C' 'C' 'C'
 'B' 'B' 'B' 'C' 'B' 'B' 'B' 'B' 'B' 'B' 'C' 'C' 'C' 'B' 'C' 'C' 'C' 'A'
 'C' 'C' 'B' 'B' 'B' 'C' 'B' 'C' 'B' 'B' 'C' 'B' 'B' 'B' 'B' 'C' 'B' 'A'
 'B' 'B' 'C' 'C' 'C' 'C' 'A' 'B' 'C' 'B' 'B' 'B' 'B' 'C' 'C' 'C' 'C' 'B'
 'A' 'C' 'C' 'C' 'C' 'C' 'B' 'B' 'B' 'C' 'A' 'B' 'B' 'C' 'B' 'C' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'C' 'C' 'B' 'C']
결과 {'A': 6, 'B': 48, 'C': 46}


In [ ]:
# 연습 #
# 심판 6명은 100명에게 점수를 1~10점으로 부여
# 최저점과 최고점을 '제외한' 점수의 평균으로 순위를 매김
# 5명만 수상

In [152]:
np.random.seed(100)
score = np.random.randint(1,11,size=(100,6))

In [153]:
np.sort(np.apply_along_axis(lambda x: np.mean(x[np.argsort(x)][1:-1]),1,score))[::-1][5]

np.float64(7.25)