In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,'3'])
lis = [1,2,'3']

In [7]:
lis[0]

1

In [22]:
a = np.array([100],dtype=np.uint8)
b = np.array([200],dtype=np.uint8)

In [25]:
a = np.array([1,2,'3'],dtype=object)

In [28]:
a = np.array([-1,1,0],dtype=bool)

In [12]:
al = [100]
bl = [200.]

In [13]:
al + bl

[100, 200.0]

In [37]:
import random

In [39]:
[ random.randint(1,100) for _ in range(100)]

[18,
 31,
 39,
 100,
 70,
 7,
 9,
 34,
 62,
 11,
 88,
 69,
 19,
 12,
 27,
 19,
 52,
 51,
 17,
 33,
 99,
 69,
 58,
 88,
 64,
 58,
 45,
 53,
 76,
 3,
 67,
 58,
 20,
 83,
 94,
 19,
 97,
 27,
 96,
 4,
 5,
 71,
 41,
 16,
 40,
 43,
 47,
 33,
 100,
 56,
 73,
 54,
 77,
 5,
 84,
 51,
 10,
 49,
 68,
 77,
 52,
 43,
 71,
 77,
 15,
 60,
 71,
 74,
 61,
 100,
 95,
 8,
 59,
 52,
 76,
 88,
 36,
 9,
 100,
 6,
 54,
 6,
 4,
 81,
 34,
 98,
 5,
 39,
 83,
 48,
 93,
 82,
 26,
 62,
 41,
 63,
 81,
 90,
 72,
 45]

In [41]:
height = np.random.randint(170,180,4)
weight = np.random.randint(70,80,4)

In [42]:
# 자신의 몸무게(kg)를 키(m)의 제곱으로 나눈 값

In [43]:
bmi = []
for i in range(4):
    bmi.append(weight[i] / (height[i]*height[i]) )

In [44]:
bmi

[0.0023781212841854932,
 0.0027335640138408304,
 0.002667487432030368,
 0.0023040020199469762]

In [45]:
weight/(height*height)

array([0.00237812, 0.00273356, 0.00266749, 0.002304  ])

In [46]:
a = np.random.randint(60,100,10)

In [48]:
np.mean(a)

82.4

In [50]:
s = 0
for i in a:
    s += i
s/len(a)

82.4

In [52]:
1/a.size*np.sum(a)

82.4

In [53]:
np.sum(a*(1/a.size))

82.40000000000002

In [56]:
a = np.random.randn(2,3)

In [62]:
a + np.random.randn(2,1)

array([[ 1.35035095,  0.75853396,  1.88487035],
       [-0.63205899, -1.8508054 , -0.77375541]])

In [65]:
a = np.random.randn(2,3)

In [74]:
a.size
a.ndim
a.dtype
a.data
a.data.obj
a.shape
type(a)

numpy.ndarray

In [79]:
np.sum(a)

-0.9915564529026673

In [82]:
a.shape

(2, 3)

In [83]:
a + np.random.randn(2,1)

array([[ 0.83068647, -0.02553973,  1.00396368],
       [-1.52530904,  1.27395447, -1.33805569]])

In [84]:
np.random.randn(2,1).shape

(2, 1)

In [85]:
np.random.randn(2).shape

(2,)

In [87]:
a + np.random.randn(3)

array([[-1.04760416,  0.18024406,  0.62396085],
       [-1.73947452,  3.14386341, -0.05393337]])

In [89]:
a + np.random.randn(1,3)

array([[-0.1326258 , -2.02350952,  0.08626561],
       [-0.82449615,  0.94010984, -0.59162862]])

In [90]:
a = np.random.randn(3,1)
b = np.random.randn(1,3)

In [91]:
(a + b).shape

(3, 3)

In [95]:
a = np.random.randn(3,1)
b = np.random.randn(3,3)

In [96]:
a = np.random.randn(5,3)

In [99]:
a + np.random.randn(5,1)

array([[-0.24383753, -2.09958071, -0.85289078],
       [-2.19469303, -2.43398571, -0.10787641],
       [-0.45885838, -0.61114106,  0.09686718],
       [-0.30747327,  0.76665966, -0.16406946],
       [ 1.41084042, -0.01522812,  1.24189998]])

In [102]:
y = np.array(5)
bool(y.shape)

False

In [244]:
x = np.arange(1,7).reshape(3,2)
y = np.arange(1,3).reshape(1,2)
print(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]]


In [255]:
print((1,3),(2,1))
print((3,1),(1,2))
print((np.random.randn(1,3) + np.random.randn(2,1)).shape)
print((np.random.randn(3,1) + np.random.randn(1,2)).shape)

(1, 3) (2, 1)
(3, 1) (1, 2)
(2, 3)
(3, 2)


In [327]:
import warnings
warnings.filterwarnings('ignore')

In [343]:
x = np.random.randn(3,2)
y = np.random.randn(2,3)

In [356]:
x = np.arange(6).reshape(3,2)
y = np.arange(6).reshape(2,3)

In [357]:
x@y

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [358]:
ret = np.zeros((x.shape[0],y.shape[1]))
cnt = 0
for i in range(x.shape[0]):
    for j in range(y.shape[1]):
        s = 0
        for k in range(y.shape[0]):
            s += x[i,k]*y[k,j]
            cnt += 1
        ret[i,j] = s
ret

array([[ 3.,  4.,  5.],
       [ 9., 14., 19.],
       [15., 24., 33.]])

In [339]:
class Array:
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.check_validation()
        
    def element_wise(self):
        if self.x.ndim == 1:
            ret = np.zeros_like(self.x)
            for i in range(self.x.size):
                ret[i] = self.x[i] + self.y[i]
            print(ret)
        else:
            ret = np.zeros_like(self.x)
            for i in range(self.x.shape[0]):
                for j in range(self.x.shape[1]):
                    ret[i,j] = self.x[i,j] + self.y[i,j]
            print(ret)
            
    def scalar_broadcast(self):
        ret = np.zeros_like(self.x)
        for i in range(self.x.shape[0]):
            for j in range(self.x.shape[1]):
                ret[i,j] = self.x[i,j] + self.y
        print(ret)
    def vector_broadcast(self):
        ret = np.zeros_like(self.x)
        for i in range(self.x.shape[0]):
            for j in range(self.x.shape[1]):
                ret[i,j] = self.x[i,j] + self.y[j]
        print(ret)
    def column_broadcast(self):
        ret = np.zeros_like(self.x)
        for i in range(self.x.shape[0]):
            for j in range(self.x.shape[1]):
                ret[i,j] = self.x[i,j] + self.y[:,j]
        print(ret)
    def row_broadcast(self):
        ret = np.zeros_like(self.x)
        for i in range(self.x.shape[0]):
            for j in range(self.x.shape[1]):
                ret[i,j] = self.x[i,j] + self.y[i,:]
        print(ret)
    def element_wise_broadcast(self,x):
        if x == 1:
            ret = np.zeros((self.x.shape[0],self.y.shape[1]))
            for i in range(self.x.shape[0]):
                for j in range(self.y.shape[1]):
                    ret[i,j] = self.x[i,:] + self.y[:,j]
        else:
            ret = np.zeros((self.y.shape[0],self.x.shape[1]))
            for i in range(self.y.shape[0]):
                for j in range(self.x.shape[1]):
                    ret[i,j] = self.x[:,j] + self.y[i,:]
        print(ret)
        
    def dot(self):
        ret = np.zeros((self.x.shape[0],self.y.shape[1]))
        
        
    def check_validation(self):
        if not isinstance(self.y,np.ndarray):
            self.scalar_broadcast()
        elif self.x.shape == self.y.shape:
            self.element_wise()
        elif self.y.ndim == 1 and self.y.size == self.x.shape[1]:
            self.vector_broadcast()
        elif 1 in self.y.shape and self.x.shape[1] == self.y.shape[1]:
            self.column_broadcast()
        elif 1 in self.y.shape and self.x.shape[0] == self.y.shape[0]:
            self.row_broadcast()
        elif 1 in self.y.shape and 1 in self.x.shape:
            if self.y.shape[0] == 1 and self.x.shape[1] == 1:
                self.element_wise_broadcast(1)
            elif self.y.shape[1] == 1 and self.x.shape[0] == 1:
                self.element_wise_broadcast(2)
        elif self.x.shape[1] == self.y.shape[0]:
            self.dot()

In [340]:
x = np.random.randn(1,3)
y = np.random.randn(2,1)

In [341]:
x+y

array([[-0.05385559, -0.84487944,  0.22469487],
       [-1.71318595, -2.5042098 , -1.43463548]])

In [342]:
arr = Array(x,y)

[[-0.05385559 -0.84487944  0.22469487]
 [-1.71318595 -2.5042098  -1.43463548]]


In [218]:
if not isinstance(y,np.ndarray) or y.shape[0]*y.shape[1] == 1:
    print("scalar broadcast")
else:
    if y.ndim == 1:
        if y.size == x.shape[1]:
            print("vector broadcast")
        else:
            print("impossible")
    else:
        if 1 in y.shape:
            if y.shape[0] == 1:
                if x.shape[1] == y.shape[1]:
                    print("column broadcast")
                else:
                    print("계산불가능")
            else:
                if x.shape[0] == y.shape[0]:
                    print("row broadcast")
                else:
                    print("계산불가능")
                

scalar broadcast


In [199]:
if y.ndim == 1:
    if y.size == x.shape[1]:
        print('계산가능')
    else:
        print("계산불가능")

계산불가능


In [187]:
if y.ndim == 2 and 1 in y.shape:
    if y.shape[0] == 1:
        if x.shape[1] == y.shape[1]:
            print(f"브로드캐스트 계산가능1")
        else:
            print(f"계산불가능2")
    else:
        if x.shape[0] == y.shape[0]:
            print(f"브로드캐스트 계산가능3")
        else:
            print(f"계산불가능4")

In [157]:
np.zeros_like(np.random.randn(3,2))
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [158]:
x = np.random.randn(3,2)
y = np.random.randn(3,2)

In [159]:
x = np.random.randn(3)
y = np.random.randn(3)
x+y

array([0.64172226, 0.169872  , 1.47408116])

In [160]:
arr = Array(x,y)

[0.64172226 0.169872   1.47408116]


In [142]:
x+y

array([[-1.10282582,  0.43361269],
       [ 0.73710989,  0.1098496 ],
       [ 0.02369533,  2.85138164]])

In [141]:
y

array([[-1.12736454,  0.78062406],
       [ 1.44530816,  0.78797231],
       [ 0.06804496,  1.61183225]])

In [168]:
np.random.randn(3,2) + np.random.randn(3,3)

array([[-2.78433632, -0.94088718],
       [ 0.16432111, -1.28525134],
       [-2.44287812, -2.54425529]])