In [31]:
#Numpy 사용
import numpy as np

In [32]:
#Numpy를 활용한 Array 생성 - 혼합 데이터 타입 (정수, 문자열)
arr = np.array([1,2,'3'])

#List 생성
li = [1,2,'3']

In [33]:
#List의 0번째(첫번째) 요소 반환 - 인덱싱 보여주기
li[0]

1

In [34]:
#Numpy Array의 0번째(첫번째) 요소 반환 - 인덱싱 보여주기
arr[0]

np.str_('1')

In [35]:
a= np.array([100],dtype=np.uint8)
b= np.array([200.],dtype=np.uint8)

In [36]:
a=np.array([1,2,'3'],dtype=object)

In [37]:
a=np.array([-1,1,0],dtype=bool)

In [38]:
a.astype(np.int32).astype(np.bool)

array([ True,  True, False])

In [39]:
a+b

array([201, 201, 200], dtype=uint8)

In [40]:
al= [100]
bl= [200.]

In [41]:
al+bl

[100, 200.0]

In [42]:
import random

In [43]:
[random.randint(1,100) for _ in range(100)]

[25,
 84,
 53,
 32,
 87,
 91,
 89,
 81,
 44,
 75,
 23,
 57,
 44,
 17,
 83,
 12,
 80,
 22,
 84,
 92,
 35,
 19,
 9,
 38,
 16,
 33,
 85,
 70,
 55,
 57,
 93,
 10,
 87,
 1,
 36,
 10,
 27,
 36,
 89,
 15,
 51,
 33,
 5,
 73,
 89,
 9,
 74,
 50,
 89,
 30,
 4,
 22,
 57,
 66,
 81,
 39,
 99,
 75,
 37,
 97,
 72,
 14,
 70,
 38,
 3,
 37,
 87,
 97,
 15,
 62,
 59,
 11,
 13,
 9,
 42,
 41,
 45,
 2,
 38,
 1,
 99,
 64,
 4,
 88,
 15,
 89,
 7,
 73,
 67,
 32,
 41,
 9,
 79,
 2,
 36,
 45,
 79,
 42,
 94,
 99]

In [44]:
np.random.randint(1,100,100)

array([ 9, 23, 34, 16, 94, 18,  5, 81, 21, 21, 73, 87, 60, 13, 75, 15, 28,
       79, 89, 21, 16, 63, 67,  9, 89, 51, 28, 14, 64, 10, 15,  1, 92, 96,
       55,  9, 64, 36, 32, 34, 72, 40, 57, 22,  1, 82, 23, 47, 53, 10, 53,
       58, 47, 62, 46, 21, 20, 55, 61, 99, 60,  4, 23, 11, 92,  5, 70, 47,
       30,  4, 20, 18, 20, 80,  4, 97, 30, 24, 34, 96, 65, 30, 96, 47, 49,
       70, 32,  4, 96, 37, 43, 54, 46, 10, 33, 47, 55, 86, 48, 37],
      dtype=int32)

In [45]:
# kg / cm**2 = BMI

height = np.random.randint(170,180,4)
weight = np.random.randint(70,80,4)

In [46]:
#4명의 BMI 계산
bmi=[]
for i in range(4):
    bmi.append(weight[i] / (height[i]*height[i]))

In [47]:
bmi

[np.float64(0.002543268595587264),
 np.float64(0.002698961937716263),
 np.float64(0.0025727555214006483),
 np.float64(0.0023671253629592224)]

In [48]:
weight/(height*height)

array([0.00254327, 0.00269896, 0.00257276, 0.00236713])

In [49]:
a=np.random.randint(60,100,10)

In [50]:
np.mean(a)

np.float64(76.1)

In [51]:
s=0

In [52]:
for i in a:
    s += i
s/len(a)

np.float64(76.1)

In [53]:
1/a.size*np.sum(a)

np.float64(76.10000000000001)

In [56]:
np.sum(a*1/a.size)

np.float64(76.10000000000001)