In [86]:
import numpy as np

In [87]:
np.__version__

'2.0.1'

##  예제 5-1-3-1  두 배열을 단순히 결합하기

In [88]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [90]:
b = np.linspace(7,13,6, dtype=np.int32).reshape(2,3)

In [91]:
b

array([[ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

-----------------------------------------------------------------------------------

In [92]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [93]:
np.concatenate([a,b], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [94]:
c = np.linspace(7,15,8, dtype=np.int32).reshape(2,4)

In [95]:
c

array([[ 7,  8,  9, 10],
       [11, 12, 13, 15]], dtype=int32)

In [96]:
try :
    np.concatenate([a,c], axis=0)
except Exception as e :
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4


-----------------------------------------------------------------------------------

In [97]:
np.concatenate([a,b], axis=0)
np.append(a,b,0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

-----------------------------------------------------------------------------------

In [98]:
np.concatenate([a,b], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]], dtype=int32)

In [99]:
np.concatenate([a,c], axis=1)

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 15]], dtype=int32)

## 예제 5-1-3-2  배열을 쌓기

In [100]:
x = np.array([1,2,3])

In [101]:
y = np.array([4,5,6])

-----------------------------------------------------------------------------------

In [102]:
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.stack([x,y],axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
z = np.array([7,8,9,10])

In [105]:
try :
    np.stack([x,z],axis=0)
except Exception as e :
    print(e)

all input arrays must have the same shape


In [106]:
np.stack([x,y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
try :
    np.stack([x,z],axis=1)
except Exception as e :
    print(e)

all input arrays must have the same shape


In [108]:
np.stack([x,y], axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## 예제 5-1-3-3  축 지정없이 배열을 쌓기

In [109]:
a = np.vstack([x,y])

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.vstack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [112]:
np.vstack([[a,a]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [113]:
b = np.hstack([x,y])

In [114]:
b

array([1, 2, 3, 4, 5, 6])

In [115]:
np.hstack([b,b])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [116]:
c = b.reshape(1,6)

In [117]:
np.hstack([c,c])

array([[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]])

In [118]:
np.row_stack([a,a])

C:\Users\kimmi\AppData\Local\Temp\ipykernel_22076\2036427324.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack([a,a])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [119]:
np.column_stack([b,b])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

## 예제 5-1-3-4  축을 확대하기

In [120]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
np.dstack([a,a])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [122]:
x = np.array([[1],[2],[3]])

In [123]:
x

array([[1],
       [2],
       [3]])

In [124]:
y = np.array([[2],[3],[4]])

In [125]:
y

array([[2],
       [3],
       [4]])

In [126]:
np.dstack([x,y])

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])