In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.1'

## 예제 3-2-1 논리식으로 검색하기 

In [3]:
L = np.random.randn(7,4)

In [4]:
L

array([[-0.3720873 ,  0.55924084, -0.3133507 ,  0.05272403],
       [-0.90451678,  0.05027145,  1.07584331,  0.62482745],
       [ 0.89006437,  0.42069949, -0.21026832, -1.25963607],
       [ 1.21060895, -1.02223227,  1.70310534,  2.6943691 ],
       [ 0.54081618, -0.21851165,  1.73133344, -1.34410767],
       [ 0.3083077 ,  0.44614813,  1.17942386, -1.21944036],
       [ 0.22258575,  2.31550821,  0.39779927,  2.21757662]])

In [5]:
L < 0

array([[ True, False,  True, False],
       [ True, False, False, False],
       [False, False,  True,  True],
       [False,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True],
       [False, False, False, False]])

In [6]:
L[ L < 0 ]

array([-0.3720873 , -0.3133507 , -0.90451678, -0.21026832, -1.25963607,
       -1.02223227, -0.21851165, -1.34410767, -1.21944036])

In [7]:
L[ L < 0 ] = 999

In [8]:
L

array([[9.99000000e+02, 5.59240837e-01, 9.99000000e+02, 5.27240282e-02],
       [9.99000000e+02, 5.02714539e-02, 1.07584331e+00, 6.24827449e-01],
       [8.90064369e-01, 4.20699488e-01, 9.99000000e+02, 9.99000000e+02],
       [1.21060895e+00, 9.99000000e+02, 1.70310534e+00, 2.69436910e+00],
       [5.40816176e-01, 9.99000000e+02, 1.73133344e+00, 9.99000000e+02],
       [3.08307701e-01, 4.46148130e-01, 1.17942386e+00, 9.99000000e+02],
       [2.22585750e-01, 2.31550821e+00, 3.97799269e-01, 2.21757662e+00]])

In [9]:
LC = L[ L == 999 ] 

In [10]:
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999.])

In [11]:
LC[0] = 1000

In [12]:
LC

array([1000.,  999.,  999.,  999.,  999.,  999.,  999.,  999.,  999.])

In [13]:
L == 1000

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [14]:
LL = L

In [15]:
np.may_share_memory(LC, L)

False

In [16]:
np.may_share_memory(LL, L)

True

--------------------------------------------------------------------------------------------

In [17]:
# 연습 #

## 각 과목 별 평균 이상의 점수만 구해서 각 사람 별 총점 구하기 --> 0으로 점수 대체 (평균 미만 시)

score = np.random.randint(60,101,(100,4))

In [18]:
score

array([[100,  65,  68,  75],
       [ 78,  96,  90,  88],
       [ 65,  74,  90,  72],
       [ 92,  77,  77,  98],
       [ 92,  72,  70,  86],
       [ 82,  69,  86,  81],
       [ 85,  80,  84,  61],
       [ 76,  94,  75,  75],
       [ 85,  68,  98,  82],
       [ 73,  95,  89,  90],
       [ 84,  92,  84,  68],
       [ 78,  65,  68,  91],
       [ 93,  78,  90,  97],
       [ 92,  94,  73,  63],
       [100,  73,  67,  64],
       [ 72,  87,  65,  80],
       [ 86,  62,  73,  64],
       [100,  87,  77,  95],
       [ 87,  82,  81,  64],
       [ 87,  90,  79,  73],
       [ 62,  96,  74,  96],
       [ 74,  71,  65,  85],
       [ 69,  98, 100,  63],
       [ 70,  60,  95,  61],
       [ 70,  92,  81,  86],
       [ 60,  96,  89,  98],
       [ 84,  66,  97,  63],
       [ 74,  60,  89,  64],
       [ 71,  94,  87,  92],
       [ 78,  73,  65,  96],
       [ 70,  97,  60,  82],
       [ 72,  68,  67,  84],
       [ 72,  86,  81,  91],
       [ 83,  75,  85,  78],
       [ 82,  

In [19]:
score[score > score.mean(0)]

array([100,  96,  90,  88,  90,  92,  98,  92,  86,  82,  86,  81,  85,
        84,  94,  85,  98,  82,  95,  89,  90,  84,  92,  84,  91,  93,
        90,  97,  92,  94, 100,  87,  80,  86, 100,  87,  95,  87,  82,
        81,  87,  90,  96,  96,  85,  98, 100,  95,  92,  81,  86,  96,
        89,  98,  84,  97,  89,  94,  87,  92,  96,  97,  82,  84,  86,
        81,  91,  83,  85,  82,  82,  86, 100,  90,  79, 100,  99,  90,
        84,  91,  84,  89, 100,  97,  96,  94,  93,  82,  99,  88,  92,
        97,  95,  92,  82, 100,  82,  94,  99,  83,  97,  94,  81, 100,
       100,  98,  92,  85,  83,  89,  85,  91,  91,  89,  96,  82,  90,
        87,  83,  81,  82,  99,  88,  81,  94,  89,  93,  94,  81,  97,
        89,  87,  96,  95,  85,  92,  81,  88, 100,  88,  92,  83,  97,
        94,  98,  90,  95,  88,  81,  91,  96,  84,  80,  85,  96,  82,
        93,  96,  91, 100,  89,  95,  89,  89,  91,  93,  88, 100,  97,
        82,  98,  91,  96,  98,  79,  95,  95,  97,  86,  80,  8

In [20]:
(score > score.mean(0))

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [ True, False,  True,  True],
       [ True, False,  True, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False,  True, False,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False, False,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False,  True, False],
 

In [25]:
(score*(score > score.mean(0))).sum(1)

array([100, 274,  90, 190, 178, 249, 169,  94, 265, 274, 260,  91, 280,
       186, 100, 167,  86, 282, 250, 177, 192,  85, 198,  95, 259, 283,
       181,  89, 273,  96, 179,  84, 258, 168, 350,  90,  79, 199,  90,
       348, 100, 287,   0,  93, 181, 277, 187, 182, 176,   0,   0, 182,
       272, 200,  98, 177, 348, 180,  96,  82, 177, 164, 181, 169, 276,
       175, 369, 272,  81, 276, 272,  94, 188, 183,  81,  91, 260, 263,
       380, 273, 180, 181, 100,  97,   0, 271, 273, 190, 263, 264,  91,
       260,  93, 264, 258, 174, 187, 263, 182, 275])

In [24]:
score.shape

(100, 4)

--------------------------------------------------------------------------------------------

In [40]:
## 변형 - 각 과목 별 평균점수 이하인 사람의 해당 과목 점수는 평균점으로 대체,
## 이후 각 개인 별 총점은?

# boolean, apply 이용

def xx(x):
    return np.where(x > x.mean(0),x,x.mean())

In [41]:
xx(score[:,0])

array([100.  ,  81.21,  81.21,  92.  ,  92.  ,  82.  ,  85.  ,  81.21,
        85.  ,  81.21,  84.  ,  81.21,  93.  ,  92.  , 100.  ,  81.21,
        86.  , 100.  ,  87.  ,  87.  ,  81.21,  81.21,  81.21,  81.21,
        81.21,  81.21,  84.  ,  81.21,  81.21,  81.21,  81.21,  81.21,
        81.21,  83.  ,  82.  ,  81.21,  81.21,  81.21,  90.  ,  84.  ,
        81.21,  97.  ,  81.21,  93.  ,  82.  ,  88.  ,  81.21,  82.  ,
        82.  ,  81.21,  81.21,  99.  ,  97.  , 100.  ,  81.21,  81.21,
        83.  ,  81.21,  81.21,  81.21,  81.21,  81.21,  82.  ,  81.21,
        94.  ,  94.  ,  97.  ,  81.21,  81.21,  88.  ,  92.  ,  94.  ,
        81.21,  95.  ,  81.21,  91.  ,  96.  ,  81.21,  93.  ,  89.  ,
        89.  ,  93.  , 100.  ,  81.21,  81.21,  82.  ,  96.  ,  81.21,
        97.  ,  81.21,  81.21,  81.21,  81.21,  86.  ,  91.  ,  92.  ,
        88.  ,  91.  , 100.  ,  98.  ])

In [42]:
xx(score[:,1])

array([ 80.2,  96. ,  80.2,  80.2,  80.2,  80.2,  80.2,  94. ,  80.2,
        95. ,  92. ,  80.2,  80.2,  94. ,  80.2,  87. ,  80.2,  87. ,
        82. ,  90. ,  96. ,  80.2,  98. ,  80.2,  92. ,  96. ,  80.2,
        80.2,  94. ,  80.2,  97. ,  80.2,  86. ,  80.2,  82. ,  80.2,
        80.2, 100. ,  80.2,  91. ,  80.2,  96. ,  80.2,  80.2,  80.2,
        92. ,  80.2,  80.2,  80.2,  80.2,  80.2,  80.2,  94. ,  80.2,
        80.2,  80.2,  89. ,  91. ,  80.2,  80.2,  90. ,  83. ,  80.2,
        88. ,  89. ,  81. ,  89. ,  95. ,  80.2, 100. ,  80.2,  80.2,
        98. ,  80.2,  80.2,  80.2,  80.2,  85. ,  96. ,  95. ,  80.2,
        80.2,  80.2,  97. ,  80.2,  80.2,  98. ,  95. ,  80.2,  82. ,
        80.2,  85. ,  80.2,  97. ,  80.2,  80.2,  99. ,  84. ,  80.2,
        83. ])

In [45]:
np.apply_along_axis(lambda x: np.where(x>x.mean(), x, x.mean()),0,score).sum(1)

array([339.79, 355.21, 330.37, 350.83, 338.83, 329.2 , 328.16, 334.8 ,
       345.2 , 355.21, 338.96, 333.04, 360.2 , 345.59, 339.79, 328.84,
       325.79, 362.63, 328.96, 336.59, 353.84, 327.04, 358.17, 335.37,
       340.21, 364.21, 340.16, 329.37, 354.21, 338.04, 340.84, 326.04,
       339.21, 327.16, 350.  , 330.37, 321.04, 360.84, 329.79, 348.  ,
       340.37, 365.96, 321.  , 332.79, 341.83, 355.96, 348.41, 341.16,
       336.83, 321.  , 321.  , 342.83, 352.63, 360.83, 340.04, 338.41,
       348.  , 340.17, 336.37, 322.37, 337.17, 325.84, 340.16, 330.84,
       354.96, 334.59, 369.  , 353.21, 321.37, 354.96, 352.2 , 333.79,
       348.17, 343.83, 321.37, 330.79, 340.2 , 344.21, 380.  , 351.96,
       339.16, 340.16, 339.79, 337.8 , 321.  , 351.2 , 353.63, 350.17,
       343.2 , 345.21, 331.37, 341.21, 333.37, 344.63, 338.2 , 334.83,
       346.59, 343.63, 342.83, 355.63])

--------------------------------------------------------------------------------------------

In [49]:
# 1,000명의 8학기 학점 평균
np.random.seed(100)
score = np.random.randint(60,101,size=(1000,8))

# 각 과목 당 학기 별 평균 미만인 점수 개수를 각 개인 별로 산출
sum(np.where((score < score.mean(0)).sum(1) > 5, "fail", "pass") == 'fail')

np.int64(137)

--------------------------------------------------------------------------------------------

In [51]:
# 연습 #

## 로또를 만 번 샀을 때, 당첨금의 기댓값

def generate_lotto_numbers():
    return np.random.choice(np.arange(1, 46), 6, replace=False)

In [52]:
def calculate_prize(matches):
    # 매칭된 숫자의 수에 따른 당첨금 예시
    if matches == 6:
        return 1000000000  # 10억 원
    elif matches == 5:
        return 50000000  # 5천만 원
    elif matches == 4:
        return 1000000  # 백만 원
    elif matches == 3:
        return 50000  # 오만 원
    else:
        return 0

In [53]:
num_trials = 10000
total_prize = 0

In [54]:
for _ in range(num_trials):
    win_number = generate_lotto_numbers()  # 당첨 번호 생성
    my_choice = generate_lotto_numbers()  # 내가 선택한 번호 생성

    # 당첨 번호와 내가 선택한 번호의 일치하는 수 계산
    matches = np.sum(np.isin(win_number, my_choice))
    
    # 당첨금 계산
    prize = calculate_prize(matches)
    total_prize += prize

# 당첨금의 기댓값 계산
expected_value = total_prize / num_trials

In [55]:
print("만 번 샀을 때의 당첨금 기댓값:", expected_value)

만 번 샀을 때의 당첨금 기댓값: 7350.0
