In [52]:
import numpy as np

In [53]:
np.__version__

'2.0.1'

## 예제 1-2-1-1  함수와 메소드 처리

In [54]:
a = np.zeros((5,5), dtype=np.int_)

In [55]:
a.shape

(5, 5)

In [56]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [57]:
a != 0

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [58]:
(a != 0).any()

np.False_

In [59]:
np.any(a !=0) 

np.False_

In [60]:
(a != 0).any

<function ndarray.any>

In [61]:
np.any

<function any at 0x000002055FACC7F0>

In [62]:
np.ndarray.any is np.core.fromnumeric.any

C:\Users\kimmi\AppData\Local\Temp\ipykernel_27012\3956599824.py:1: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.
  np.ndarray.any is np.core.fromnumeric.any


False

In [63]:
help(np.ndarray.any)

Help on method_descriptor:

any(...) unbound numpy.ndarray method
    a.any(axis=None, out=None, keepdims=False, *, where=True)

    Returns True if any of the elements of `a` evaluate to True.

    Refer to `numpy.any` for full documentation.

    See Also
    --------
    numpy.any : equivalent function



In [64]:
help(np.any)

Help on _ArrayFunctionDispatcher in module numpy:

any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
    Test whether any array element along a given axis evaluates to True.

    Returns single boolean if `axis` is ``None``

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (``axis=None``) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the expected ou

In [65]:
import numpy as np

In [66]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [67]:
set(dir(np))

{'False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [68]:
np_ = set(dir(np))

In [69]:
nd_ = set(dir(np.ndarray))

In [70]:
npd_ = np_ & nd_

In [71]:
len(npd_)

48

In [72]:
x= np.array([1,2,3])

In [73]:
np.sum(x) == x.sum

np.False_

In [74]:
npd_

{'__dir__',
 '__doc__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'cumprod',
 'cumsum',
 'diagonal',
 'dot',
 'dtype',
 'imag',
 'max',
 'mean',
 'min',
 'ndim',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'sum',
 'swapaxes',
 'take',
 'trace',
 'transpose',
 'var'}

In [75]:
count = 0
for i in list(npd_) :
    count +=1
    print(i, end=" ")
    if count % 5  == 0 :
        print()
        

astype all take conjugate sum 
__dir__ shape argsort choose size 
sort reshape put std resize 
ravel diagonal dtype trace dot 
prod argpartition mean cumsum real 
copy max round ptp nonzero 
conj ndim cumprod clip argmin 
transpose swapaxes partition var argmax 
__doc__ squeeze repeat compress min 
any searchsorted imag 

## 예제 1-2-2-1   유니버셜 함수

In [76]:
a = dir(np)

In [77]:
np.ufunc

numpy.ufunc

In [78]:
np.Tester

AttributeError: module 'numpy' has no attribute 'Tester'

In [ ]:
count = 0

for i in a :
    
    if i == "Tester" :
        continue
    
    if type(np.__dict__[i])  == np.ufunc :
        print(i, end=" ")
        count += 1 
        if count % 5 == 0 :
            print()
    

In [ ]:
import types

In [ ]:
count = 0

for i in a :
    if i == "Tester" :
        continue
    
    if type(np.__dict__[i])  == types.FunctionType :
        count += 1 

print(count)

In [ ]:
type(np.add)

In [ ]:
type(np.sort)

In [ ]:
set(dir(np.add)) - set(dir(np.sort))

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
np.add(a,a)

In [ ]:
np.add.accumulate(a)

## 예제 1-2-3-1  벡터화 연산

In [79]:
a = np.arange(6,10)

In [80]:
a

array([6, 7, 8, 9])

In [81]:
b = np.arange(10,14)

In [82]:
b

array([10, 11, 12, 13])

In [83]:
c = a * b

In [84]:
c

array([ 60,  77,  96, 117])

In [85]:
d = a[:, np.newaxis]

In [86]:
d

array([[6],
       [7],
       [8],
       [9]])

In [87]:
d.shape

(4, 1)

In [88]:
e = b[np.newaxis,:]

In [89]:
e

array([[10, 11, 12, 13]])

In [90]:
e.shape

(1, 4)

In [91]:
f = d @ e

In [92]:
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [93]:
d.dot(e)

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

## 예제 1-2-4-1   축에 따른  연산

In [ ]:
a2 = np.array([1,2,3,4])

In [ ]:
a2

In [ ]:
a2 = a2.reshape(2,2)

In [ ]:
a2

In [ ]:
np.sum(a2)

In [ ]:
np.sum(a2, axis=0)

In [ ]:
np.sum(a2, axis=1)

In [ ]:
a3 = np.arange(1,9)

In [ ]:
a3

In [ ]:
a3 = a3.reshape(2,2,2)

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3[0]

In [ ]:
a3[1]

In [ ]:
np.sum(a3)

In [ ]:
np.sum(a3, axis=0)

In [ ]:
np.sum(a3, axis=1)

In [ ]:
np.sum(a3, axis=2)

## 예제 1-2-5-1   원소별로 연산하기

In [ ]:
a = np.array([4,5])

In [ ]:
a.shape

In [ ]:
b = np.array([3,4,6])

In [ ]:
b.shape

In [ ]:
try :
    a+b
except Exception as e :
    print(e)

In [ ]:
a = np.append(a,[6])

In [ ]:
a.shape

In [ ]:
a + b

In [ ]:
a2 = np.array([[1,2,3],[3,4,5]])

In [ ]:
b2 = np.array([1,2])

In [ ]:
try :
    a2 + b2
except Exception as e :
    print(e)

In [ ]:
b2 = np.append(b2,[3])

In [ ]:
b2.shape

In [ ]:
a2 + b2