In [60]:
import numpy as np

In [61]:
np.__version__

'2.0.1'

## 예제 1-3-1-1  배열의 할당 알아보기

In [62]:
a = np.array([[1,2],[3,4]])

In [63]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [64]:
b = a

In [118]:
id(a)

1457728666288

In [119]:
id(b)

1457728667056

In [66]:
a is b

True

In [67]:
a is b.base

False

In [68]:
b[0] = 999

In [69]:
a

array([[999, 999],
       [  3,   4]])

In [70]:
b

array([[999, 999],
       [  3,   4]])

## 예제 1-3-1-2  메모리 공유 

In [71]:
f = np.array([4,5,6,7,8])

In [72]:
e = f.copy()

In [73]:
e.base is None

True

In [74]:
g = f[:]

In [75]:
g.base

array([4, 5, 6, 7, 8])

In [76]:
g.base is f

True

In [120]:
# g와 f라는 함수에 메모리를 공유하느냐? 라는 내용
np.may_share_memory(g,f)

True

In [78]:
g[1] = 99999

In [79]:
g

array([    4, 99999,     6,     7,     8])

In [80]:
f

array([    4, 99999,     6,     7,     8])

In [81]:
h = f.view()

In [82]:
h

array([    4, 99999,     6,     7,     8])

In [83]:
h.base is f

True

In [84]:
np.may_share_memory(h,f)

True

In [85]:
a = np.array([1,3,5,7])

In [86]:
b = np.array(a,copy=True)

In [87]:
b.base is None

True

In [88]:
c = np.array(a)

In [89]:
c.base is None

True

## 예제 1-3-2-1  배열 생성과 변경 

In [90]:
aa = np.array([1,2,3,4,5,6,7])

In [91]:
aa_c = np.sort(aa, axis=0)

In [92]:
aa_c

array([1, 2, 3, 4, 5, 6, 7])

In [93]:
aa_c.base is None

True

In [94]:
aa[6] = 0

In [95]:
aa.sort()

In [96]:
aa

array([0, 1, 2, 3, 4, 5, 6])

## 예제 1-3-3-1  검색과 슬라이싱

In [97]:
l = list(range(1,10))

In [98]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
index = 1 

In [100]:
l.__getitem__(index)

2

In [101]:
index = slice(1,3)

In [102]:
l.__getitem__(index)

[2, 3]

In [103]:
a = np.array([1,2,3,4,5,6,7])

In [104]:
index = 1 

In [105]:
a.__getitem__(index)

np.int64(2)

In [106]:
index = slice(1,3)

In [107]:
a.__getitem__(index)

array([2, 3])

In [108]:
index = 1 

In [109]:
a.__getitem__(index)

np.int64(2)

In [110]:
index=[1]

In [111]:
a.__getitem__(index)

array([2])

In [112]:
index = a < 4

In [113]:
index

array([ True,  True,  True, False, False, False, False])

In [114]:
a.__getitem__(index)

array([1, 2, 3])

In [115]:
index = a < 3

In [116]:
a.__setitem__(index , 9080)

In [117]:
a

array([9080, 9080,    3,    4,    5,    6,    7])