In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.1'

## 예제 2-2-1 행렬 알아보기

In [3]:
# 2개의 차원
A  = np.array([[43],[44]])

In [4]:
type(A)

numpy.ndarray

In [5]:
A

array([[43],
       [44]])

In [6]:
A.dtype

dtype('int64')

In [7]:
A.ndim

2

In [8]:
A.shape

(2, 1)

In [9]:
# tuple type을 만듦 
shape = (3,4)

In [10]:
dtype = np.int64

In [11]:
B = np.full(shape,7, dtype)

In [12]:
B

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [13]:
#사이즈
np.full((10,7),10,np.int_)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])