In [31]:
import numpy as np

In [32]:
np.__version__

'2.0.1'

## 예제 2-1-4-1  벡터 크기 계산하기 

In [33]:
v = np.arange(3,5)

In [34]:
v

array([3, 4])

In [35]:
v_p = np.power(v,2)

In [36]:
v_p

array([ 9, 16])

In [37]:
v_r = np.sqrt(np.sum(v_p))

In [38]:
v_r

np.float64(5.0)

In [39]:
np.hypot(v[0],v[1])

np.float64(5.0)

In [40]:
np.linalg.norm(v)

np.float64(5.0)

In [41]:
v3 = np.arange(60).reshape(6,10)

In [42]:
v3.shape

(6, 10)

## 예제 2-1-4-2  단위벡터 계산하기 

In [43]:
e1 = np.array([1,0,0])

In [44]:
np.linalg.norm(e1)

np.float64(1.0)

In [45]:
e2 = np.array([0,1,0])

In [46]:
np.linalg.norm(e2)

np.float64(1.0)

In [47]:
e3 = np.array([0,0,1])

In [48]:
np.linalg.norm(e3)

np.float64(1.0)

In [49]:
v_3 = np.array([1,2,3])

In [50]:
v_3_n = np.linalg.norm(v_3)

In [51]:
v_3_n

np.float64(3.7416573867739413)

In [52]:
v_3_u = v_3 / v_3_n

In [53]:
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [54]:
np.linalg.norm(v_3_u)

np.float64(1.0)

In [55]:
def normal(v) :
    return v / np.sqrt(np.dot(v,v))

In [56]:
v_4 = np.array([1,2,3,4])

In [57]:
v_4_u = normal(v_4)

In [58]:
v_4_u

array([0.18257419, 0.36514837, 0.54772256, 0.73029674])

In [59]:
np.linalg.norm(v_4_u)

np.float64(0.9999999999999999)

In [60]:
np.round(np.linalg.norm(v_4_u),10)

np.float64(1.0)