In [42]:
import numpy as np

In [43]:
np.__version__

'2.0.1'

## einsum 

    https://stackoverflow.com/questions/26089893/understanding-numpys-einsum
    
    https://ita9naiwa.github.io/numeric%20calculation/2018/11/10/Einsum.html

In [44]:
np.einsum

<function einsum at 0x00000151B9F26930>

## 예제 4-6-3-1  두 개  2차원 배열의 연산 처리하기

In [45]:
E = np.arange(10).reshape(2,5)

In [46]:
F = np.arange(5, 15).reshape(2,5)

In [47]:
np.einsum('ij,ij->ij', E, F)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [48]:
np.einsum('ij,jk->ik', E, F.T)

array([[ 80, 130],
       [255, 430]])

In [49]:
np.dot(E, F.T)

array([[ 80, 130],
       [255, 430]])

In [83]:
y = np.random.randn(4,3,2)

In [85]:
np.einsum("ijk->jk",y).shape

(3, 2)

### 두 배열의 곱연산 후에 축 별로 합산하기

In [50]:
A_ = np.array([0, 1, 2])

In [51]:
B_ = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [52]:
np.einsum('i,ij->', A_, B_)

np.int64(98)

In [53]:
np.sum(A_) + np.sum(B_)

np.int64(69)

In [54]:
(A_.reshape(3,1) * B_).sum()

np.int64(98)

In [55]:
A_[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [56]:
A_[:, np.newaxis] * B_

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [57]:
(A_[:, np.newaxis] * B_).sum()

np.int64(98)

In [58]:
np.einsum('i,ij->i', A_, B_)

array([ 0, 22, 76])

In [59]:
(A_[:, np.newaxis] * B_).sum(axis=1)

array([ 0, 22, 76])

In [60]:
np.einsum('i,ij->j', A_, B_)

array([20, 23, 26, 29])

In [61]:
(A_[:, np.newaxis] * B_).sum(axis=0)

array([20, 23, 26, 29])

### 전치 행렬 변환 후 곱하기

In [62]:
x = np.array([1,2,3,4]).reshape(2,2)

In [63]:
x.T

array([[1, 3],
       [2, 4]])

In [64]:
try :
    np.einsum('ii,ii->ii', x,x)
except Exception as e :
    print(e)

einstein sum subscripts string includes output subscript 'i' multiple times


In [65]:
np.einsum('ij,ij->ij', x,x)

array([[ 1,  4],
       [ 9, 16]])

In [66]:
x * x

array([[ 1,  4],
       [ 9, 16]])

In [67]:
np.einsum('ij,ji->ij', x,x)

array([[ 1,  6],
       [ 6, 16]])

In [68]:
x * x.T

array([[ 1,  6],
       [ 6, 16]])

In [69]:
np.einsum('ij,jk->ik', x,x.T)

array([[ 5, 11],
       [11, 25]])

In [70]:
np.dot(x ,x.T)

array([[ 5, 11],
       [11, 25]])

### 첫번째 행렬의 행을 기준으로 sum(aij*bji)

In [71]:
x = np.array([1,3,4,2]).reshape(2,2)

In [72]:
y = np.array([1,2,4,2]).reshape(2,2)

In [73]:
np.dot(x,y)

array([[13,  8],
       [12, 12]])

In [74]:
np.dot(x,y).sum(axis=1)

array([21, 24])

In [75]:
np.einsum("ij,jk->i",x,y)

array([21, 24])

In [76]:
np.dot(x[0], y[:,0]) + np.dot(x[0], y[:,1])

np.int64(21)

In [77]:
np.dot(x[1], y[:,0]) + np.dot(x[1], y[:,1])

np.int64(24)

### 두 번째 행렬의 열을 기준으로 sum(bkj*aji)

In [78]:
np.dot(x,y).sum(axis=0)

array([25, 20])

In [79]:
np.einsum("ij,jk->k",x,y)

array([25, 20])

In [80]:
y.T

array([[1, 4],
       [2, 2]])

In [81]:
np.dot(y.T[0], x[0]) + np.dot(y.T[0], x[1]) 

np.int64(25)

In [82]:
np.dot(y.T[1], x[0]) + np.dot(y.T[1], x[1]) 

np.int64(20)